### ISSUE TITLE
Add new batch of Community Organisations

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap.org#122]
Please add the following Community Organisations:

Jednadvacet
Bitcoin Jamii
Bitcoin 4 Iranians
Bitcoin Bulgaria

I'll add the tags to the communities once done so that they don't disappear in the meantime.

The Community Organisations should also be listed in alphabetical order in the drop down.

**Comment by secondl1ght** [comment]
Ok these are now added - I also added `enogtyve`. You can check out this commit to see the org IDs to add but I followed the standard convention. https://github.com/teambtcmap/btcmap.org/commit/b4dbf99baa424cbcc01398ed306a1e6c543788e0

I made a note to myself to refactor this code in the future to make it automated so that orgs get added whenever the tag gets populated in the backend. This will be smoother and remove the manual work and won't cause these files to get out of control in size. But it's lower priority right now since we don't add new orgs very often.

You can close this issue once you add the tags to the backend and we confirm they are working as expected.

**Comment by dadofsambonzuki** [comment]
All done, except Bulgaria. I will cover that off in the Bulgaria issues.
