### ISSUE TITLE
Third party payment app hides native payment method

### ISSUE THREAD

**Issue by VojtechMyslivec** [teambtcmap/btcmap.org#139]
**Describe the bug**
When a merchant accepts both native payment method (e.g. via lightning) and third party app, only "third party app" icon is shown.

**To Reproduce**
See e.g. [Pivovarský klub Benedict](https://btcmap.org/merchant/node:585219608) or [Café Decada](https://btcmap.org/merchant/node:2035703150). Both places accept bitcoin directly via lightning and the `payment:lightning=yes` tag is set. The latter accepts bolt cards as well (`payment:lightning_contactless=yes`). However, neither "lightning accepted" nor "contactless accepted" icons are shown.

**Expected behavior**
"lightning accepted", "contactless accepted" etc icons are shown when appropriate tags are set even if third party app is possible (but not required).

**Screenshots**
![Screenshot from 2024-04-11 10-08-58](https://github.com/teambtcmap/btcmap.org/assets/11145995/5579b770-29dc-408f-b6a7-ff4eca22c99b)
![Screenshot from 2024-04-11 10-11-44](https://github.com/teambtcmap/btcmap.org/assets/11145995/62c51ca5-35e9-43d0-906c-69478705168a)

**Additional context**

**Comment by secondl1ght** [comment]
Hi @VojtechMyslivec, yes you are correct about this. The Querko? team started using a new tag called `payment:lightning:requires_companion_app` which indicates that a third party app is required. So this tag should be removed if the merchant accepts native lightning. However, because it seems like this dataset is very likely to go unmaintained by the owners I will make an adjustment. If any native bitcoin options are present then we can ignore this outdated tag. Thanks!
