### ISSUE TITLE
Km unit scale text cut off on initial map load (tiny)

### ISSUE THREAD

**Issue by chris-pollard** [teambtcmap/btcmap.org#46]
**
<img width="115" alt="Screen Shot 2022-10-07 at 6 37 02 pm" src="https://user-images.githubusercontent.com/28696655/194604403-179c955d-6416-40cf-a6f7-e0ef1aa16dde.png">
Description:**

This is a small bug. At least at the first load zoom level for the map, the kilometre text is cut off ever so slightly.

**To Reproduce:**

1. Go to 'btcmap.org/map'
2. See error in bottom left corner on desktop.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

<!--
- Device: macbook Air
- OS: macOS 12.6
- Browser : Brave (chromium)

**Comment by secondl1ght** [comment]
Hey @chris-pollard 👋🏼 thanks for reporting this, I will look into it a fix for it.

**Comment by secondl1ght** [comment]
So because this is a scale bar we cannot change the width of it - I think the only solution to solve this edge case is to make the font size smaller on the scale bars. Here is a screenshot of a font size that is smaller and fixes this issue. Can you have a look and let me know what you think?

- Would you rather have this issue fixed and potentially have the scale bar text harder to read?
- Or leave this issue as-is and keep the font size the same?

![image](https://user-images.githubusercontent.com/85003930/194670368-5b0d80c1-5637-42a8-811e-1bec29beeb6b.png)

**Comment by dadofsambonzuki** [comment]
Reduce txt size for me.

Is this an upstream Leaflet bug or did we just pick a too large text size
to begin with?

**Comment by secondl1ght** [comment]
Ok will do - this is an upstream leaflet bug because I have not changed any defaults to the scale bar. I will also put in a PR on their repo to propose a fix.

**Comment by secondl1ght** [comment]
This is fixed now and I also opened a PR upstream for Leaflet: https://github.com/Leaflet/Leaflet/pull/8543
