### ISSUE TITLE
Missing OpenStreetMap attribution

### ISSUE THREAD

**Issue by habi** [teambtcmap/btcmap.org#84]
As an avid OpenStreetMap contributor, I am pleased to see that you are using OpenStreetMap on your website and prominently link to OSM data for the single merchants/amenities on it.

However, I noticed that the map seems to lack the proper credit.
OpenStreetMap's license requires that you both credit OpenStreetMap and make users aware of the data license (by linking to our copyright page). For more information, see: https://www.openstreetmap.org/copyright

The correct attribution helps to avoid misunderstandings about the source of the map or data, as well as what others are allowed to do with it. If you need help making the changes or have further questions, 
feel free to ask in one of OpenStreetMap's communication channels: https://wiki.openstreetmap.org/wiki/Contact

More importantly attribution helps us spread the word about
OpenStreetMap and attract new contributors and build the community.
This is incredibly important to improving the quality of the database that you and millions of others rely on.

**Comment by habi** [comment]
Here's a screenshot from an iPhone 12 mini, with iOS 16.5.

![image](https://user-images.githubusercontent.com/1651235/232983562-3735b5dc-1c26-4a93-8acb-f35868ecadd5.png)

**Comment by habi** [comment]
If it's a simple out-of viewport issue, this can be fixed like so: https://github.com/openstreetmap-polska/openaedmap-frontend/commit/72a30611ada2aeda07c99ce8b7ed387d8e701e3c

**Comment by secondl1ght** [comment]
Thanks for reporting @habi, yes this is a bug. If you look on desktop or another screen size there is an attribution present. It looks like on this device it gets cutoff due to the viewport issue you described. I will make a fix for this. We also link to OSM in many other places on the web app like the main landing page, About Us page, Wiki, README and more. Since our project is essentially an OpenStreetMap project we try to educate as many people as possible about how it works so we can create more mappers. We also became a Bronze sponsor of OSM last year to show our support for the project. We are big fans! Our main goal is to improve the data quality for everyone so we can create useful applications using that information. I will get a fix in for this this week.

**Comment by secondl1ght** [comment]
@habi this should be fixed now, could you please confirm before we close the ticket? Thanks!

**Comment by habi** [comment]
Indeed all good, thanks for the very speedy fix!

![image](https://user-images.githubusercontent.com/1651235/233269027-963fc2c8-f3e6-4705-958c-1910a33d1ed1.jpeg)
